apiVersion: v1
kind: Secret
metadata:
  name: openldap
  namespace: company
type: Opaque
data:
  adminpassword: YTZOdVZDQmJyQjRINkRTZg==
  log-level: MjU2
  organization: VUVUIFVuaXRlZA==
  domain: dWV0dW5pdGVkLmNvbQ==
  base-dn: ZGM9dWV0dW5pdGVkLGRjPWNvbQ==
  read-only-user: ZmFsc2U=
  rfc-schema: ZmFsc2U=
  backend: bWRi
  replication: ZmFsc2U=
  existing-config: ZmFsc2U=
  remove-config-after-setup: dHJ1ZQ==
  ssl-helper-prefix: bGRhcA==
