apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: uet-kube-rc
spec:
  replicas: 2
  selector: 
    matchLabels: # Change here
      app: uet-kube # RC manage pod by label of pod
  template:
    metadata:
      labels:
        app: uet-kube # Label of pod
    spec:
      containers:
      - image: dutvmta/kube-hello:v2
        name: uet-kube 
        ports:
          - containerPort: 3000
