apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: uet-kube-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uet-kube
  template:
    metadata:
      labels:
        app: uet-kube
    spec:
      containers:
      - image: dutvmta/uet-kube
        name: uet-kube
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    app: uet-kube
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30123