apiVersion: v1 
kind: Pod 
metadata:
  name: uet-kube # Name of the pod
  labels:
    environment: dev
    project: uet
spec:
  containers:
    - image: dutvmta/uet-kube # Image to create the container
      name: uet-kube # Name of the container
      ports:
        - containerPort: 3000 # The port the app is listening on 
          protocol: TCP
